"""add password column to the organization feild

Revision ID: bc1e1b311570
Revises: c1c25ac1a227
Create Date: 2023-10-02 06:30:36.828066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1e1b311570'
down_revision: Union[str, None] = 'c1c25ac1a227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'password')
    # ### end Alembic commands ###
