"""set organization_id instead of admin_id in subscribed_services

Revision ID: e20d2619bc78
Revises: 648967266207
Create Date: 2023-10-07 12:42:34.955767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20d2619bc78'
down_revision: Union[str, None] = '648967266207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribed_services', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_constraint('subscribed_services_admin_id_fkey', 'subscribed_services', type_='foreignkey')
    op.create_foreign_key(None, 'subscribed_services', 'admins', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscribed_services', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribed_services', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscribed_services', type_='foreignkey')
    op.create_foreign_key('subscribed_services_admin_id_fkey', 'subscribed_services', 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subscribed_services', 'organization_id')
    # ### end Alembic commands ###
